### ISSUE TITLE
Error after:  INFO - Structure dataset: multiple unique compositions found, trying to construct convex hull

### ISSUE THREAD

**Issue by siamak-attarian** [ICAMS/python-ace#6]
Hi,

I am training a potential for a 4 component system. I have used the same data to fit another potential (MTP) which worked fine, so I know that the data are fine. I'm getting the following error when fitting with pacemaker. (I put the whole report, but made the part that the error starts in bold font).

Any idea what may cause this?

Thanks,
Siamak

2022-05-03 23:16:17,116 - root - INFO - Redirecting log into file log.txt
2022-05-03 23:16:17,124 - root - INFO - Start pacemaker
2022-05-03 23:16:17,125 - root - INFO - pacemaker/pyace version: 0.2.7
2022-05-03 23:16:17,126 - root - INFO - ace_evaluator   version: 2021.10.25
2022-05-03 23:16:17,127 - root - INFO - Loading input.yaml...
2022-05-03 23:16:17,193 - pyace.generalfit - INFO - Set numpy random seed to 42
2022-05-03 23:16:17,615 - pyace.generalfit - INFO - Target potential shape constructed from dictionary, it contains 5552
 functions
2022-05-03 23:18:21,798 - pyace.generalfit - INFO - tensorpot_version: 0.2.0+19.gfa5b8b0
2022-05-03 23:18:21,819 - pyace.generalfit - INFO - User name automatically identified: sattarian
2022-05-03 23:18:21,824 - pyace.preparedata - INFO - Search for cache ref-file: fourthtrain.pckl.gzip
2022-05-03 23:18:21,828 - pyace.preparedata - INFO - fourthtrain.pckl.gzip found, try to load
2022-05-03 23:18:21,831 - pyace.preparedata - INFO - Loading dataframe from pickle file fourthtrain.pckl.gzip (3.2MiB)
2022-05-03 23:18:22,232 - pyace.preparedata - INFO - Transforming to DataFrameWithMetadata
2022-05-03 23:18:22,235 - pyace.preparedata - INFO - Setting up structures dataframe - please be patient...
2022-05-03 23:18:22,335 - pyace.preparedata - INFO - Processing structures dataframe. Shape: (846, 5)
2022-05-03 23:18:22,339 - pyace.preparedata - INFO - Total number of atoms: 90472
2022-05-03 23:18:22,342 - pyace.preparedata - INFO - Mean number of atoms per structure: 106.9
2022-05-03 23:18:22,346 - pyace.preparedata - INFO - 'energy' columns found
2022-05-03 23:18:22,349 - pyace.preparedata - INFO - 'forces' columns found
2022-05-03 23:18:22,352 - pyace.preparedata - INFO - 'pbc' columns extraction from 'ase_atoms'
2022-05-03 23:18:22,366 - pyace.preparedata - INFO - 'cell' column found
2022-05-03 23:18:22,370 - pyace.preparedata - INFO - 'energy_corrected' column found
2022-05-03 23:18:22,377 - pyace.preparedata - INFO - 'energy_corrected_per_atom' column extraction
2022-05-03 23:18:22,382 - pyace.preparedata - INFO - Min energy per atom: -5.352 eV/atom
2022-05-03 23:18:22,385 - pyace.preparedata - INFO - Max energy per atom: -4.305 eV/atom
2022-05-03 23:18:22,389 - pyace.preparedata - INFO - Min abs energy per atom: 4.305 eV/atom
2022-05-03 23:18:22,393 - pyace.preparedata - INFO - Max abs energy per atom: 5.352 eV/atom
2022-05-03 23:18:22,396 - pyace.preparedata - INFO - ASE atoms ('ase_atoms' column) are already in dataframe
2022-05-03 23:18:22,399 - pyace.preparedata - INFO - Attaching SinglePointCalculator to ASE atoms...
2022-05-03 23:18:22,778 - pyace.preparedata - INFO - Attaching SinglePointCalcualtor to ASE atoms...done within 0.375462
 sec (0.00415004 ms/at)
2022-05-03 23:18:22,781 - pyace.preparedata - INFO - Atomic environment representation construction...
2022-05-03 23:18:22,785 - pyace.preparedata - INFO - Building 'tp_atoms' (dataset size 846, cutoff=10.0A)...
2022-05-03 23:18:30,433 - pyace.preparedata - INFO - Dataframe size after transform: 846
2022-05-03 23:18:30,438 - pyace.preparedata - INFO - Atomic environment representation construction...done within 7.6532
 sec (0.0846 ms/atom)
2022-05-03 23:18:30,443 - pyace.preparedata - INFO - Saving processed raw dataframe into fourthtrain.pckl.gzip
2022-05-03 23:18:30,446 - pyace.preparedata - INFO - Writing fit pickle file: /home/sattarian/ACE/training/train22/fourt
htrain.pckl.gzip
2022-05-03 23:20:44,308 - pyace.preparedata - INFO - Saved to file /home/sattarian/ACE/training/train22/fourthtrain.pckl
.gzip (39.4MiB)
2022-05-03 23:20:44,323 - pyace.preparedata - INFO - Apply weights policy: EnergyBasedWeightingPolicy(nfit=10000, energy
=convex_hull, DElow=1.0, DEup=10.0, DFup=50.0, DE=1.0, DF=1.0, wlow=0.75, reftype=all,seed=42)
2022-05-03 23:20:44,326 - pyace.preparedata - INFO - Keeping bulk and cluster data
2022-05-03 23:20:44,329 - pyace.preparedata - INFO - No cutoff for EnergyBasedWeightingPolicy is provided, no structures
 outside cutoff that will now be removed
2022-05-03 23:20:44,332 - pyace.preparedata - INFO - EnergyBasedWeightingPolicy: energy reference frame - convex hull di
stance (if possible)
2022-05-03 23:20:44,405 - pyace.preparedata - WARNING - No pure element energy for Be is available, assuming 0  eV/atom
2022-05-03 23:20:44,409 - pyace.preparedata - WARNING - No pure element energy for Cr is available, assuming 0  eV/atom
2022-05-03 23:20:44,416 - pyace.preparedata - WARNING - No pure element energy for F is available, assuming 0  eV/atom
2022-05-03 23:20:44,423 - pyace.preparedata - WARNING - No pure element energy for Li is available, assuming 0  eV/atom
**2022-05-03 23:20:44,428 - pyace.preparedata - INFO - Structure dataset: multiple unique compositions found, trying to co
nstruct convex hull**
Traceback (most recent call last):
  File "/mnt/cephfs/software/sattarian/anaconda3/envs/ACE/bin/pacemaker", line 332, in <module>
    main(sys.argv[1:])
  File "/mnt/cephfs/software/sattarian/anaconda3/envs/ACE/bin/pacemaker", line 269, in main
    general_fit = GeneralACEFit(potential_config=potential_config, fit_config=fit_config, data_config=data_config,
  File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/generalfit.py", line 303, in __init__
    self.fitting_data = get_fitting_dataset(evaluator_name=self.evaluator_name,
  File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/preparedata.py", line 1132, in get_fitt
ing_dataset
    df = spec.get_fit_dataframe(force_query=force_query, ignore_weights=force_weighting)
  File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/preparedata.py", line 636, in get_fit_d
ataframe
    self.df = self.weights_policy.generate_weights(self.df)
  File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/preparedata.py", line 731, in generate_
weights
    compute_convexhull_dist(df)  # generate "e_chull_dist_per_atom" column
  File "/software/sattarian/anaconda3/envs/ACE/lib/python3.8/site-packages/pyace/preparedata.py", line 924, in compute_c
onvexhull_dist
    hull = ConvexHull(chull_values)
  File "_qhull.pyx", line 2436, in scipy.spatial._qhull.ConvexHull.__init__
  File "_qhull.pyx", line 357, in scipy.spatial._qhull._Qhull.__init__
scipy.spatial._qhull.QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the int
erior point)

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 706984386  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _max-width  1  Error-roundoff 6.7e-15  _one-merge 6e-14  _near-inside 3e-13
  Visible-distance 4e-14  U-max-coplanar 4e-14  Width-outside 8e-14
  _wide-facet 2.4e-13  _maxoutside 8e-14

precision problems (corrected unless 'Q0' or an error)
      5 degenerate hyperplanes recomputed with gaussian elimination
      5 nearly singular or axis-parallel hyperplanes
      5 zero divisors during back substitute
    852 zero divisors during gaussian elimination

The input to qhull appears to be less than 4 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p598(v5):  0.13 0.027  0.59  -4.3
- p661(v4):  0.13 0.027  0.59  -5.4
- p100(v3):  0.13 0.019  0.58  -5.2
- p0(v2):  0.14 0.0098  0.58  -5.2
- p200(v1):  0.13 0.027  0.59  -5.3

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 6.7e-15.  The center point, facets and distances
to the center point are as follows:

center point   0.1302   0.0221   0.5872   -5.057

facet p661 p100 p0 p200 distance= -3.5e-18
facet p598 p100 p0 p200 distance= -3.5e-18
facet p598 p661 p0 p200 distance= -3.5e-18
facet p598 p661 p100 p200 distance= -3.5e-18
facet p598 p661 p100 p0 distance= -3.5e-18

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:    0.1273    0.1373  difference= 0.009982
  1:  0.009804   0.02727  difference= 0.01747
  2:    0.5784    0.5909  difference= 0.01248
  3:    -5.352  -2.225e-308  difference= 5.352

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 6.7e-15.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.

**Comment by yury-lysogorskiy** [comment]
It seems to be a problem with building a convex hull for multispecies case. Please try to use in `input.yaml` option
```
...
fit:
   weighting: {
    ...
   energy: cohesive
    ...
   }
```
to apply energy-based weighting policy depending on the absolute energy and not on the distance to the convex hull
as described  [here](https://pacemaker.readthedocs.io/en/latest/pacemaker/inputfile/#fitting_settings).
Alternatively, you could try to to remove(comment out) the `weighting` section completely, then unofirm weighting policy will be applied.

**Comment by siamak-attarian** [comment]
Thank you. I'll try playing with the possible weighting options.
