### ISSUE TITLE
unhashable type: 'list'

### ISSUE THREAD

**Issue by Snehal-V2** [ICAMS/python-ace#84]
HI,im trying to run input.yaml file through pacemaker but im getting this error. I dont know how to use it.  
cutoff: 7.0 # cutoff for neighbour list construction
seed: 42  # random seed

#################################################################
#################################################################
metadata:
  origin: "Automatically generated input"

#################################################################
#################################################################
potential:
  deltaSplineBins: 0.001
  elements: ['S', 'S', 'W', 'W']

  embeddings:
    ALL: {
      npot: 'FinnisSinclairShiftedScaled',
      fs_parameters: [ 1, 1, 1, 0.5 ],
      ndensity: 2,
    }

  bonds:
    ALL: {
      radbase: SBessel,
      radparameters: [ 5.25 ],
      rcut: 7.0,
      dcut: 0.01,
      NameOfCutoffFunction: cos,
    }

  functions:
    number_of_functions_per_element: 700
    UNARY:   { nradmax_by_orders: [ 15, 6, 4, 3, 2, 2 ], lmax_by_orders: [ 0 , 3, 3, 2, 2, 1 ]}
    BINARY:  { nradmax_by_orders: [ 15, 6, 3, 2, 2, 1 ], lmax_by_orders: [ 0 , 3, 2, 1, 1, 0 ]}
    TERNARY: { nradmax_by_orders: [ 15, 3, 3, 2, 1 ],    lmax_by_orders: [ 0 , 2, 2, 1, 1 ], }
    ALL:     { nradmax_by_orders: [ 15, 3, 2, 1, 1 ],    lmax_by_orders: [ 0 , 2, 2, 1, 1 ] }

#################################################################
#################################################################
data:
  filename: md_fixed.pckl.gzip       # force to read reference pickled dataframe from given file
  
  #  aug_factor: 1e-4 # common prefactor for weights of augmented structures
  # reference_energy: auto

#################################################################
#################################################################
fit:
  loss: { kappa: 0.3, L1_coeffs: 1e-8,  L2_coeffs: 1e-8}
  # if kappa: auto, then it will be determined from the variation of energy per atom and forces norms in train set

  weighting: { type: EnergyBasedWeightingPolicy, DElow: 1.0, DEup: 10.0, DFup: 50.0, DE: 1.0, DF: 1.0, wlow: 0.75, energy: convex_hull, reftype: all,seed: 42}

  optimizer: BFGS # or L-BFGS-B

  ## maximum number of minimize iterations
  maxiter: 2000

  ## additional options for scipy.minimize
  #  options: {maxcor: 100}

  ## Automatically find the smallest interatomic distance in dataset  and set inner cutoff for ZBL to it
  repulsion: auto

  #  ladder_step: 100
  #  ladder_type: power_order

  # Early stopping
  # min_relative_train_loss_per_iter: 5e-5
  # min_relative_test_loss_per_iter: 1e-5
  # early_stopping_patience: 200

#################################################################
#################################################################
backend:
  evaluator: tensorpot
  batch_size: 100
  display_step: 50

**Comment by yury-lysogorskiy** [comment]
for some reason you do have elements: ['S', 'S', 'W', 'W']  - repetitive elements here.
try to run `pacemaker -t` to generate propert input file automatically

**Comment by naveenmohandas** [comment]
I am also facing this issue, running `pacemaker -t` doesn't seem to fix the issue.  I get the following error 

```
Generating 'input.yaml'
Enter training dataset filename (ex.: data.pckl.gzip, [TAB] - autocompletion): test
test.pckl.gzip           test_cycle_metrics.txt   test_ladder_metrics.txt  test_metrics.txt
Enter training dataset filename (ex.: data.pckl.gzip, [TAB] - autocompletion): test
test.pckl.gzip           test_cycle_metrics.txt   test_ladder_metrics.txt  test_metrics.txt
Enter training dataset filename (ex.: data.pckl.gzip, [TAB] - autocompletion): test.pckl.gzip
Enter test set fraction or size (ex.: 0.05 or [ENTER] - no test set): 0.2
Please enter list of elements (ex.: "Cu", "AlNi", [ENTER] - determine from dataset):
Trying to load test.pckl.gzip
Determining available elements...
Found elements:  ['Fe']
Number of elements:  1
Elements:  ['Fe']
Enter number of functions per element ([ENTER] - default 700):
Number of functions per element:  700
Enter cutoff (Angstrom, default:7.0):
Cutoff:  7.0
Enter weighting scheme type - `uniform` or `energy` ([ENTER] - `uniform`):
Use UniformWeightingPolicy
Input file is written into `input.yaml`
(ace_new) nkaruthodimoha@int4: test_6/ -> pacemaker input.yaml
{path}/.conda/envs/ace_new/bin/pacemaker:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2025/09/29 17:10:36 I - Redirecting log into file log.txt
2025/09/29 17:10:36 I - Start pacemaker
2025/09/29 17:10:36 I - Hostname: int4.local.snellius.surf.nl
2025/09/29 17:10:36 I - Username: nkaruthodimoha
2025/09/29 17:10:36 I - pacemaker/pyace version: 0.2.7+172.gd1c213a
2025/09/29 17:10:36 I - ace_evaluator   version: 2023.11.25
2025/09/29 17:10:36 I - Loading input.yaml...
2025/09/29 17:10:36 I - Set numpy random seed to 42
2025/09/29 17:10:36 I - Number of functions in target potential is limited to maximum 700 functions per element  for 1 elements (1 blocks)
2025/09/29 17:10:36 I - Resulted potential contains 700 functions
2025/09/29 17:10:36 I - Target potential shape constructed from dictionary, it contains 700 functions
2025/09/29 17:10:38 E - unhashable type: 'list'
2025/09/29 17:10:38 I - User name automatically identified: nkaruthodimoha
2025/09/29 17:10:38 I - Search for dataset file(s): ['test.pckl.gzip']
2025/09/29 17:10:38 I - #1/1: try to load test.pckl.gzip
2025/09/29 17:10:38 I - Loading dataframe from pickle file test.pckl.gzip (52.5KiB)
2025/09/29 17:10:38 I -  10 structures found
2025/09/29 17:10:38 I - Processing structures dataframe. Shape: (10, 6)
2025/09/29 17:10:38 I - Total number of atoms: 1574
2025/09/29 17:10:38 I - Mean number of atoms per structure: 157.4
2025/09/29 17:10:38 I - Min/max energy per atom: [-8.212, -7.379] eV/atom
2025/09/29 17:10:38 I - Min/max abs energy per atom: [7.379, 8.212] eV/atom
{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/preparedata.py:61: FutureWarning: Please use atoms.calc = calc
  atoms.set_calculator(calc)
2025/09/29 17:10:38 I - Attaching SinglePointCalculator to ASE atoms...done
2025/09/29 17:10:38 I - Construction of neighbour lists...
2025/09/29 17:10:38 I - Building 'tp_atoms' (dataset size 10, cutoff=7.000A)...
2025/09/29 17:10:38 I - Dataframe size after transform: 10
2025/09/29 17:10:38 I - Construction of neighbour lists...done within 0.0669 sec (0.0425 ms/atom)
2025/09/29 17:10:38 I - Splitting out test dataset (test_size = 0.2) from main dataset(10 samples)
2025/09/29 17:10:38 I - Processing structures dataframe. Shape: (2, 9)
2025/09/29 17:10:38 I - Total number of atoms: 300
2025/09/29 17:10:38 I - Mean number of atoms per structure: 150.0
2025/09/29 17:10:38 I - Min/max energy per atom: [-7.986, -7.385] eV/atom
2025/09/29 17:10:38 I - Min/max abs energy per atom: [7.385, 7.986] eV/atom
{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/preparedata.py:61: FutureWarning: Please use atoms.calc = calc
  atoms.set_calculator(calc)
2025/09/29 17:10:38 I - Attaching SinglePointCalculator to ASE atoms...done
2025/09/29 17:10:38 I - Construction of neighbour lists...
2025/09/29 17:10:38 I - Building 'tp_atoms' (dataset size 2, cutoff=7.000A)...
2025/09/29 17:10:38 I - Dataframe size after transform: 2
2025/09/29 17:10:38 I - Construction of neighbour lists...done within 0.0196 sec (0.0653 ms/atom)
2025/09/29 17:10:38 I - No weighting policy is specified, setting default weighting policy
2025/09/29 17:10:38 I - Apply weights policy: UniformWeightingPolicy()
2025/09/29 17:10:38 I - Dataset saved into fitting_data_info.pckl.gzip
2025/09/29 17:10:38 I - Dataset saved into test_data_info.pckl.gzip
2025/09/29 17:10:38 I - Plotting train energy-forces distribution
2025/09/29 17:10:39 I - Plotting test energy-forces distribution
2025/09/29 17:10:40 I - Fitting dataset size: 8 structures / 1274 atoms
2025/09/29 17:10:40 I - Test dataset size: 2 structures / 300 atoms
2025/09/29 17:10:40 I - 'Single-shot' fitting
2025/09/29 17:10:40 I - Cycle fitting loop
2025/09/29 17:10:40 I - Number of fit attempts: 0/1
2025/09/29 17:10:40 I - Total number of functions: 700 / number of parameters: 1760
2025/09/29 17:10:40 I - Running fit backend
2025/09/29 17:10:40 I - Trainable parameters: {('Fe',): ['func', 'radial']}
Traceback (most recent call last):
  File "{path}/.conda/envs/ace_new/bin/pacemaker", line 401, in <module>
    main(sys.argv[1:])
  File "{path}/.conda/envs/ace_new/bin/pacemaker", line 248, in main
    general_fit.fit()
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/generalfit.py", line 478, in fit
    self.target_bbasisconfig = self.cycle_fitting(self.target_bbasisconfig)
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/generalfit.py", line 564, in cycle_fitting
    current_bbasisconfig = self.fit_backend.fit(
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/fitadapter.py", line 129, in fit
    raise e
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/fitadapter.py", line 95, in fit
    self.setup_tensorpot(bbasisconfig, dataframe, loss_spec, trainable_parameters_dict)
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/pyace/fitadapter.py", line 171, in setup_tensorpot
    from tensorpotential.potentials.ace import ACE
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorpotential/__init__.py", line 2, in <module>
    from . import potentials
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorpotential/potentials/__init__.py", line 2, in <module>
    from . import ace
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorpotential/potentials/ace.py", line 3, in <module>
    import tensorflow as tf
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/__init__.py", line 49, in <module>
    from tensorflow._api.v2 import __internal__
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/python/autograph/utils/__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/python/autograph/utils/context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "{path}/.conda/envs/ace_new/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5950, in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 433, in Optional
    return Union[arg, type(None)]
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "{path}/.conda/envs/ace_new/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

```

My input yaml file is as below

```
cutoff: 7.0 # cutoff for neighbour list construction
seed: 42  # random seed

#################################################################
## Metadata section
#################################################################
metadata:
  origin: "Automatically generated input"

#################################################################
## Potential definition section
#################################################################
potential:
  deltaSplineBins: 0.001
  elements: ['Fe']

  embeddings:
    ALL: {
      npot: 'FinnisSinclairShiftedScaled',
      fs_parameters: [ 1, 1, 1, 0.5 ],
      ndensity: 2,
    }

  bonds:
    ALL: {
      radbase: SBessel,
      radparameters: [ 5.25 ],
      rcut: 7.0,
      dcut: 0.01,
      NameOfCutoffFunction: cos,
    }

  functions:
    number_of_functions_per_element: 700
    UNARY:   { nradmax_by_orders: [ 15, 6, 4, 3, 2, 2 ], lmax_by_orders: [ 0 , 3, 3, 2, 2, 1 ]}
    BINARY:  { nradmax_by_orders: [ 15, 6, 3, 2, 2, 1 ], lmax_by_orders: [ 0 , 3, 2, 1, 1, 0 ]}
    TERNARY: { nradmax_by_orders: [ 15, 3, 3, 2, 1 ],    lmax_by_orders: [ 0 , 2, 2, 1, 1 ], }
    ALL:     { nradmax_by_orders: [ 15, 3, 2, 1, 1 ],    lmax_by_orders: [ 0 , 2, 2, 1, 1 ] }


#################################################################
## Dataset specification section
#################################################################
data:
  filename: test.pckl.gzip       # force to read reference pickled dataframe from given file
  test_size: 0.2
  #  aug_factor: 1e-4 # common prefactor for weights of augmented structures
  # reference_energy: auto

#################################################################
## Fit specification section
#################################################################
fit:
  loss: { kappa: 0.3, L1_coeffs: 1e-8,  L2_coeffs: 1e-8}
  # if kappa: auto, then it will be determined from the variation of energy per atom and forces norms in train set

  

  optimizer: BFGS # or L-BFGS-B

  ## maximum number of minimize iterations
  maxiter: 2000

  ## additional options for scipy.minimize
  #  options: {maxcor: 100}

  ## Automatically find the smallest interatomic distance in dataset  and set inner cutoff for ZBL to it
  repulsion: auto

  #  ladder_step: 100
  #  ladder_type: power_order

  # Early stopping
  # min_relative_train_loss_per_iter: 5e-5
  # min_relative_test_loss_per_iter: 1e-5
  # early_stopping_patience: 200

#################################################################
## Backend specification section
#################################################################
backend:
  evaluator: tensorpot
  batch_size: 100
  display_step: 50


```

could you let me know how to fix this issue?
